import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import { Web3Modal } from "../context/web3-provider";
import MainLayout from "@/layout/main-layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const bricolage = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "RockPaperScissors",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${bricolage.className} bg-mellow-300`}>
				<Web3Modal>
					<MainLayout>{children}</MainLayout>
				</Web3Modal>
			</body>
		</html>
	);
}
